### ISSUE TITLE
보스 및 적 생각하기

### ISSUE THREAD

**Issue by Merseong** [KU-CATDOG/super-doodle#3]
최소 두개의 보스

필요한것
1. 외형
2. 이동 속도
3. 기믹(선택사항)
4. 같이 나올 적의 유무 / 적의 모습 등

**Comment by cse21jh** [comment]
1. 일단 구체적인 외형은 생각한 게 없으나 스테이지가 바뀌는 느낌으로 보스 외형이 바뀌면 맵 외형도 조금 달라졌으면 좋겠습니다
2.
3. 무기가 스폰돼서 플레이어가 맵을 돌다가 (시간적 여유가 될 경우) 추가로 키를 더 눌러서 무기를 교체하고, 무기마다 보스나 잡몹 타격 이미지가 바뀌는 것도 재미있을 것 같은데 이 경우 리소서분이 갈릴 것 같아서... ㅜㅜ
4. 잡몹도 넣자는 이야기가 있던데 잡몹 있어도 좋을 것 같습니다 있다면 보스 외형이랑 비슷한 계열로 가지 않을까 싶어요

**Comment by Merseong** [comment]
를 이제 wiki에 잘 정리하면 될거같아요!
@cse21jh 
[wiki 링크](https://github.com/KU-CATDOG/super-doodle/wiki/%EB%B3%B4%EC%8A%A42)
